/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

/* Jeder neue Term in der Fibonacci-Sequenz wird durch Hinzufügen der vorherigen beiden Terms generiert. Wenn Sie mit 1 und 2 beginnen, lauten die ersten 10 Begriffe:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
Wenn Sie die Terme in der Fibonacci-Sequenz betrachten, deren Werte vier Millionen nicht überschreiten, ermitteln Sie die Summe der Terme mit geradem Wert. */

#include <stdio.h>

int main(void)
{
    int n1, n2, sum, sum1 = 0;

    n1 = 1;
    n2 = 2;
    sum1 = 2;

    while (sum < 4000000)
    {

        sum = n1+n2;
        n1 = n2;
        n2 = sum;

        if(sum%2==0)
        {
            sum1 = sum+sum1;
        }

        printf("%d %d\n", sum1, sum);
    }



    return 0;
}
